### ISSUE TITLE
Reloading altered console cog

### ISSUE THREAD

**Issue by Succubyss** [Mihitoko/discord.py-Console#10]
So, using console_cog.py and test.py from Examples, I inserted a token and made one addition, a `reload_concog` command:
```python
@console.command()
async def reload_concog():
    console.reload_extension("console_cog")
```

The idea is that reload_concog would be used when I make a change to console_cog. For this test I just edited the cog_test command. However, if I make an edit and then reload the cog with `reload_concog`, it remains the same.

If I change reload_extension to unload_extension, the cog_test command will no longer work as expected, so there's nothing wrong with how I'm doing it. It just seems that the old `ConsoleCog` class isn't being discarded.

Am I doing something wrong, or does dpyConsole's reload_extension function need to be modified?

**Comment by Mihitoko** [comment]
Hey @Succubyss 
True im a bit bussy lately.
But ill try to take some time at the weekend to look at the open issues.
(Since there are a couple of open once)

If you need the bugfix fast feel free to open a PR.

But ill look into it at the weekend.

**Comment by Mihitoko** [comment]
Yes #12 should fix this.
Try it out urself if everything works as expected ill close the issue.

**Comment by Succubyss** [comment]
Apologies for the late reply, I think I must've accidentally marked the email notification as read. I've been terribly busy as of late as well.

I gave this a test today and it seems to be working, but strangely it throws an exception, or at least I think it's an exception?

I type `reload con_main` into the console and hit Enter, then ...
```text
  File "D:\DiscordBot\run.py", line 188, in reload
    await console.reload_extension(f"cogs.{extension}")
```
It gives me this output. It's strange, I've never seen an exception that just tells me the line but doesn't give me any more details than that.

However, running a command proves that the reload command actually worked because the command will be updated.

Also, I noticed that exiting the bot script in any way other than using Ctrl+C or `os._exit(0)` will now cause errors. `quit()` will do nothing at first but if you run it again it spits out a ton of different errors. And, `exit()` causes a bunch of these:

```
ValueError: I/O operation on closed file.
Traceback (most recent call last):
  File "D:\DiscordBot\venv\Lib\site-packages\dpyConsole\console.py", line 106, in listen
    console_in = shlex.split(self.input.readline())
                             ^^^^^^^^^^^^^^^^^^^^^
ValueError: I/O operation on closed file.
```

I've tried other ways to try and gracefully stop the script without causing errors, but to no avail. For instance, if I try to run `bot.close()` beforehand, e.g. `await asyncio.wait(asyncio.create_task(client.close()))`, I'll get `raise TypeError(f"expect a list of futures, not {type(fs).__name__}")`,

**Comment by Mihitoko** [comment]
You await the cog reload but it is a snyc function so it errors.
I messed up and oonly printed TB to console so it is not showing what excacly is wrong ill fix that in the future.

For the error when exiting the cleanest solution would be to rewrite the input logic.

**Comment by Succubyss** [comment]
> You await the cog reload but it is a snyc function so it errors. I messed up and oonly printed TB to console so it is not showing what excacly is wrong ill fix that in the future.

I see. discord.py's cog reload function _is_ an async function, so that threw me off.
