### ISSUE TITLE
[question] reloading cogs

### ISSUE THREAD

**Issue by chromatic-aberration** [Mihitoko/discord.py-Console#2]
I don't see any reload_cog or remove_cog function for console Cogs, is it not possible for them? Or is there any different intended way to do it?

**Comment by Mihitoko** [comment]
Unfortunately this is not implemented yet.
But implement this would make a lot of sense.
Ill work on that if i got some spare time or feel free to create a pull request yourself. 😄

**Comment by Mihitoko** [comment]
I added reload, and unload behavior to the "console".
Ill close this issue now.
